#!/bin/bash
grails clean
grails war
rm -fr /var/lib/tomcat6/webapps/ianandco /var/lib/tomcat6/webapps/ianandco.war
mv target/ianandco.war   /var/lib/tomcat6/webapps
mv ianandco.war ROOT.war
/etc/init.d/tomcat6 stop
/etc/init.d/tomcat6 start
